### PR TITLE
Fisher

### PR DESCRIPTION
**Pull request by thehrh**
@tarlen5: Hello Tim, could you please have a look at this?

### CODE REVIEW

**Comment by tarlen5** [comment]
@thehrh Thanks, Thomas, I'll look at it as soon as I can this week.

Best,
Tim

**Comment by tarlen5** [comment]
Hi Thomas, I have just made a bunch of minor changes to my master branch that cleaned up a bunch of (mostly) little things. Can I ask you to please pull in these changes (from my master) to your ```fisher``` branch, then commit and push your changes onto here, so that when I merge your branch, there will be a minimum of merge conflicts? Thanks!

**Comment by thehrh** [comment]
Done!

**Comment by tarlen5** [comment]
Hi @thehrh and @sboeser, I am going to merge this PR into my master branch. I have looked it all over and it seems like it's doing what it is supposed to (I'm sure you all have tested it much more than I have anyway). However, it would be nice to clean up the code more when you get a chance-i.e. remove the

`import numpy as n`

and replace it with `np` everywhere, and make it conform a little more to the pisa coding conventions. Since this is mostly a stylistic (not functional) change, it should go a little on the back-burner for now, but eventually, we should do this (clean up the code).

It'd also be nice to add a notebook or script somewhere that takes the output of `FisherAnalysis.py` and calculates the significance and outputs the breakdown of the importance of each systematic, as is done in the PaPA code. (I'd do something similar for the LLR analysis, but it is typically run on a cluster since it takes so much longer than the Fisher method that I'm not sure how worthwhile it'd be!)

Thanks!

**Comment by jllanfranchi** [comment]
Hi @thehrh @sboeser and @tarlen5, just going to weigh in on the last request above, and urge that, while I don't care what the UI is, a *function* should be provided that actually does the work.

And in general: it is awkward and slow integrating shell-style Python scripts with other Python code; it's even worse with an IPython nb. You can make whatever user interface for the function you want: Call the function from within a shell-style script or an IPython nb which handles pulling in options and settings from the user and various files and provides the average user a pretty and usable interface (that's great); but the meat of the functionality should live inside a function (or class, your pick) that preferably takes as arguments Python data types (i.e., not filenames) so the user of the function can decide whether to pass data around within his code as files or as Python datatypes.

Then when I want to use things in a non-standard way, like run the code a thousand times, I'm not hacking together my own version of the same script (duplicating code and possibly introducing bugs, or not using and therefore not implicitly testing the "standard" way of doing things) or calling Python shell scripts from my Python code, when I could just be importing and calling a function directly.

My two cents.

**Comment by thehrh** [comment]
Hi @tarlen5, @jllanfranchi, I have tried to address your suggestions. The Fisher analysis is now performed by a dedicated function that is not dependent on any input from the shell; a basic notebook demonstrates this. You can find the changes here: https://github.com/thehrh/pisa/tree/fisher.

**Comment by jllanfranchi** [comment]
Definitely seems to have addressed my concerns there; thanks!

**Pull request merged**
